In [12]:
import datetime

%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import xarray as xr
from netCDF4 import Dataset
import os
import seaborn as sns
import time
import bisect
from collections import OrderedDict
from collections import deque


import plotly.graph_objects as go

In [4]:
da=xr.open_dataset(r'C:\Users\\futil\OneDrive\GIZ\Internship\seb_test_ring\\rose\maker\AllCo2.nc')
da

<xarray.Dataset>
Dimensions:   (ID: 7878, RoseDir: 16, Turb: 4, hgt: 4, normData: 2)
Coordinates:
    lat       (ID) float64 ...
    lon       (ID) float32 ...
  * ID        (ID) int64 0 1 2 3 4 5 6 7 ... 7871 7872 7873 7874 7875 7876 7877
  * hgt       (hgt) int32 50 80 100 150
  * normData  (normData) object 'loc' 'scale'
  * Turb      (Turb) object 'Turbine 1' 'Turbine 2' 'Turbine 3' 'Turbine 4'
  * RoseDir   (RoseDir) object 'N' 'NNE' 'NE' 'ENE' 'E' ... 'W' 'WNW' 'NW' 'NNW'
Data variables:
    CF        (ID, hgt, Turb) float64 ...
    Power     (ID, hgt, Turb) float64 ...
    Rose      (ID, hgt, RoseDir) float64 ...
    Norn      (ID, hgt, normData) float32 ...

In [10]:
Names=np.array(da['RoseDir'])
Names

array(['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW',
       'WSW', 'W', 'WNW', 'NW', 'NNW'], dtype=object)

In [18]:
da['Rose'].sel(ID=0,hgt=50)

<xarray.DataArray 'Rose' (RoseDir: 16)>
array([ 6.966,  5.654,  5.175,  7.038, 10.278, 13.958, 14.669, 11.007,  6.041,
        3.347,  2.683,  2.24 ,  1.663,  1.511,  2.446,  5.322])
Coordinates:
    lat      float64 ...
    lon      float32 ...
    ID       int64 0
    hgt      int32 50
  * RoseDir  (RoseDir) object 'N' 'NNE' 'NE' 'ENE' 'E' ... 'W' 'WNW' 'NW' 'NNW'

In [42]:
Names=list(np.array(da['RoseDir']))
Names.append(Names[0])
Names

['N',
 'NNE',
 'NE',
 'ENE',
 'E',
 'ESE',
 'SE',
 'SSE',
 'S',
 'SSW',
 'SW',
 'WSW',
 'W',
 'WNW',
 'NW',
 'NNW',
 'N']

In [41]:
rose=da['Rose'].sel(ID=0,hgt=Height)
rose

<xarray.DataArray 'Rose' (RoseDir: 16)>
array([ 6.966,  5.654,  5.175,  7.038, 10.278, 13.958, 14.669, 11.007,  6.041,
        3.347,  2.683,  2.24 ,  1.663,  1.511,  2.446,  5.322])
Coordinates:
    lat      float64 ...
    lon      float32 ...
    ID       int64 0
    hgt      int32 50
  * RoseDir  (RoseDir) object 'N' 'NNE' 'NE' 'ENE' 'E' ... 'W' 'WNW' 'NW' 'NNW'

In [46]:
Roll = 2
RoseTraces=[]
NamesDeque = deque(Names)
NamesDeque.extend(NamesDeque[0])


DropdownHeight=[50]
for Height in DropdownHeight:

    rose=list(np.array(da['Rose'].sel(ID=0,hgt=Height)))
    rose.append(rose[0])
    Names=list(np.array(da['RoseDir']))
    Names.append(Names[0])


    RoseTraces.append(
        go.Scatterpolar( r=rose, theta=Names, fill='toself',name=Height))




Roselayout=go.Layout(
            polar=dict(
                radialaxis=dict(
                    visible=True,
                    #range="atao",
                    ticksuffix='%',

                )),
            showlegend=True,
            polar_angularaxis_rotation=90,)

# return {
#         'data': RoseTraces,
#         'layout': go.Layout(
#             polar=dict(
#                 radialaxis=dict(
#                     visible=True,
#                     #range="atao",
#                     ticksuffix='%',

#                 )),
#             showlegend=True,
#             orientation=90,  # not moving

#     )

# }

In [47]:
figure4 = go.Figure(data=RoseTraces,layout=Roselayout)

In [48]:
figure4.show()

In [ ]:
da

array([   0.,    0.,   29.,  171.,  389.,  703., 1139., 1682., 2205.,
       2541., 2669., 2697., 2700., 2700., 2700., 2700., 2700., 2700.,
       2700., 2700., 2700., 2700., 2700., 2700., 2700.,    0.])

In [53]:
PowerTurbDF = pd.read_csv(r"C:\Users\futil\OneDrive\GIZ\Internship\seb_test_ring\WPC\PowerTurb4.csv")
PowerTurbDF

Speed  Turbine 1  Turbine 2  Turbine 3  Turbine 4
0       1        0.0        0.0        0.0        0.0
1       2        0.0        0.0        0.0        0.0
2       3       29.0       25.0       33.0        0.0
3       4      171.0      171.0      194.0       77.0
4       5      389.0      389.0      442.0      190.0
5       6      703.0      704.0      802.0      353.0
6       7     1139.0     1136.0     1298.0      581.0
7       8     1682.0     1674.0     1915.0      886.0
8       9     2205.0     2173.0     2533.0     1273.0
9      10     2541.0     2518.0     2881.0     1710.0
10     11     2669.0     2696.0     2997.0     2145.0
11     12     2697.0     2766.0     3000.0     2544.0
12     13     2700.0     2780.0     3000.0     2837.0
13     14     2700.0     2780.0     3000.0     2965.0
14     15     2700.0     2780.0     3000.0     2995.0
15     16     2700.0     2780.0     3000.0     3000.0
16     17     2700.0     2780.0     3000.0     3000.0
17     18     2700.0     2780.0     3000.0     3000.0
18     19     2700.0     2780.0     3000.0     3000.0
19     20     2700.0     2780.0     3000.0     3000.0
20     21     2700.0     2780.0        0.0     3000.0
21     22     2700.0     2780.0        0.0     3000.0
22     23     2700.0     2780.0        0.0     3000.0
23     24     2700.0     2780.0        0.0     3000.0
24     25     2700.0     2780.0        0.0     3000.0
25     26        0.0        0.0        0.0        0.0

In [55]:
da

<xarray.Dataset>
Dimensions:   (ID: 7878, RoseDir: 16, Turb: 4, hgt: 4, normData: 2)
Coordinates:
    lat       (ID) float64 ...
    lon       (ID) float32 ...
  * ID        (ID) int64 0 1 2 3 4 5 6 7 ... 7871 7872 7873 7874 7875 7876 7877
  * hgt       (hgt) int32 50 80 100 150
  * normData  (normData) object 'loc' 'scale'
  * Turb      (Turb) object 'Turbine 1' 'Turbine 2' 'Turbine 3' 'Turbine 4'
  * RoseDir   (RoseDir) object 'N' 'NNE' 'NE' 'ENE' 'E' ... 'W' 'WNW' 'NW' 'NNW'
Data variables:
    CF        (ID, hgt, Turb) float64 ...
    Power     (ID, hgt, Turb) float64 ...
    Rose      (ID, hgt, RoseDir) float64 ...
    Norn      (ID, hgt, normData) float32 ...

In [66]:
TurbPower=np.array([np.array(PowerTurbDF['Turbine 1']),
                    np.array(PowerTurbDF['Turbine 2']),
                    np.array(PowerTurbDF['Turbine 3']),
                    np.array(PowerTurbDF['Turbine 4']),])
TurbPower

array([[   0.,    0.,   29.,  171.,  389.,  703., 1139., 1682., 2205.,
        2541., 2669., 2697., 2700., 2700., 2700., 2700., 2700., 2700.,
        2700., 2700., 2700., 2700., 2700., 2700., 2700.,    0.],
       [   0.,    0.,   25.,  171.,  389.,  704., 1136., 1674., 2173.,
        2518., 2696., 2766., 2780., 2780., 2780., 2780., 2780., 2780.,
        2780., 2780., 2780., 2780., 2780., 2780., 2780.,    0.],
       [   0.,    0.,   33.,  194.,  442.,  802., 1298., 1915., 2533.,
        2881., 2997., 3000., 3000., 3000., 3000., 3000., 3000., 3000.,
        3000., 3000.,    0.,    0.,    0.,    0.,    0.,    0.],
       [   0.,    0.,    0.,   77.,  190.,  353.,  581.,  886., 1273.,
        1710., 2145., 2544., 2837., 2965., 2995., 3000., 3000., 3000.,
        3000., 3000., 3000., 3000., 3000., 3000., 3000.,    0.]])

In [77]:
da5 = xr.Dataset({
    "CF": (["ID", 'hgt', 'Turb'], np.array(da['CF'])),
    "Power": (["ID", 'hgt', 'Turb'], np.array(da['Power'])),
    "Rose": (["ID", 'hgt', 'RoseDir'],  np.array(da['Rose']),),
    "Norn": (["ID", 'hgt', 'normData'], np.array(da['Norn'])),
    "TurbPower": (["Turb", 'turbSdp'], TurbPower),
    },

    coords={
        "lat": (["ID"], np.array(da['lat'])),
        "lon": (["ID"], np.array(da['lon'])),

        'ID': np.array(da['ID']),
        'hgt': da['hgt'],
        'normData': ["loc", "scale"],
        'RoseDir':np.array(da['RoseDir']),
        'Turb': ['Turbine 1', 'Turbine 2', 'Turbine 3', 'Turbine 4'],
        'turbSdp':list(PowerTurbDF['Speed']),
        

    }, )

In [76]:
np.array(da['RoseDir'])

array(['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW',
       'WSW', 'W', 'WNW', 'NW', 'NNW'], dtype=object)

In [ ]:
list(PowerTurbDF['Speed'])

array([[   0.,    0.,   29.,  171.,  389.,  703., 1139., 1682., 2205.,
        2541., 2669., 2697., 2700., 2700., 2700., 2700., 2700., 2700.,
        2700., 2700., 2700., 2700., 2700., 2700., 2700.,    0.],
       [   0.,    0.,   25.,  171.,  389.,  704., 1136., 1674., 2173.,
        2518., 2696., 2766., 2780., 2780., 2780., 2780., 2780., 2780.,
        2780., 2780., 2780., 2780., 2780., 2780., 2780.,    0.],
       [   0.,    0.,   33.,  194.,  442.,  802., 1298., 1915., 2533.,
        2881., 2997., 3000., 3000., 3000., 3000., 3000., 3000., 3000.,
        3000., 3000.,    0.,    0.,    0.,    0.,    0.,    0.],
       [   0.,    0.,    0.,   77.,  190.,  353.,  581.,  886., 1273.,
        1710., 2145., 2544., 2837., 2965., 2995., 3000., 3000., 3000.,
        3000., 3000., 3000., 3000., 3000., 3000., 3000.,    0.]])

In [73]:
da["RoseDir"]

<xarray.DataArray 'RoseDir' (RoseDir: 16)>
array(['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW',
       'WSW', 'W', 'WNW', 'NW', 'NNW'], dtype=object)
Coordinates:
  * RoseDir  (RoseDir) object 'N' 'NNE' 'NE' 'ENE' 'E' ... 'W' 'WNW' 'NW' 'NNW'

In [65]:
np.shape(TurbPower)

(4, 26)

In [78]:
da5

<xarray.Dataset>
Dimensions:    (ID: 7878, RoseDir: 16, Turb: 4, hgt: 4, normData: 2, turbSdp: 26)
Coordinates:
    lat        (ID) float64 -20.59 -20.6 -20.61 -20.63 ... -23.29 -23.29 -23.29
    lon        (ID) float32 31.659058 31.612762 ... 31.013031 32.450745
  * ID         (ID) int64 0 1 2 3 4 5 6 7 ... 7871 7872 7873 7874 7875 7876 7877
  * hgt        (hgt) int32 50 80 100 150
  * normData   (normData) <U5 'loc' 'scale'
  * RoseDir    (RoseDir) object 'N' 'NNE' 'NE' 'ENE' ... 'W' 'WNW' 'NW' 'NNW'
  * Turb       (Turb) <U9 'Turbine 1' 'Turbine 2' 'Turbine 3' 'Turbine 4'
  * turbSdp    (turbSdp) int32 1 2 3 4 5 6 7 8 9 ... 18 19 20 21 22 23 24 25 26
Data variables:
    CF         (ID, hgt, Turb) float64 15.83 15.32 16.23 ... 44.77 46.99 27.67
    Power      (ID, hgt, Turb) float64 3.744 3.731 4.265 ... 10.9 12.35 7.271
    Rose       (ID, hgt, RoseDir) float64 6.966 5.654 5.175 ... 1.154 2.39 4.01
    Norn       (ID, hgt, normData) float32 4.451085 1.9601946 ... 3.260042
    TurbPo

In [79]:
da5.to_netcdf(r'C:\Users\futil\OneDrive\GIZ\Internship\seb_test_ring\rose\maker\AllCoTurb.nc')

In [80]:
da5['turbSdp']

<xarray.DataArray 'turbSdp' (turbSdp: 26)>
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26])
Coordinates:
  * turbSdp  (turbSdp) int32 1 2 3 4 5 6 7 8 9 10 ... 18 19 20 21 22 23 24 25 26

In [82]:
da5['TurbPower'].sel(Turb='Turbine 1')

<xarray.DataArray 'TurbPower' (turbSdp: 26)>
array([   0.,    0.,   29.,  171.,  389.,  703., 1139., 1682., 2205.,
       2541., 2669., 2697., 2700., 2700., 2700., 2700., 2700., 2700.,
       2700., 2700., 2700., 2700., 2700., 2700., 2700.,    0.])
Coordinates:
    Turb     <U9 'Turbine 1'
  * turbSdp  (turbSdp) int32 1 2 3 4 5 6 7 8 9 10 ... 18 19 20 21 22 23 24 25 26